#!/bin/bash
echo -e "                                           " | pv -qL 400
echo -e "\e[36m $(sed '1!d' .im.txt)" | pv -qL 40
echo -e "\e[32m $(sed '2!d' .im.txt)" | pv -qL 20
echo -e "\e[31m $(sed '3!d' .im.txt)" | pv -qL 20
echo -e "\e[32m $(sed '4!d' .im.txt)" | pv -qL 20
echo -e "\e[33m $(sed '5!d' .im.txt)" | pv -qL 700
#echo -e "\e[34m $(sed '4!d' im.txt)" | pv -qL 20
echo -e "\e[36m $(sed '6!d' .im.txt)" | pv -qL 20
echo -e "\e[37m $(sed '7!d' .im.txt)" | pv -qL 20
echo -e "\e[34m $(sed '8!d' .im.txt)" | pv -qL 20
echo -e "\e[33m $(sed '9!d' .im.txt)" | pv -qL 20
echo -e "\e[31m $(sed '10!d' .im.txt)" | pv -qL 20
echo -e "\e[31m $(sed '11!d' .im.txt)" | pv -qL 20
echo -e "\e[33m $(sed '12!d' .im.txt)" | pv -qL 20
echo -e "\e[32m $(sed '13!d' .im.txt)" | pv -qL 20
echo -e "\e[31m $(sed '14!d' .im.txt)" | pv -qL 20


